from typing import Any


class EventsSystem:
    @staticmethod
    def register_event(event_name, event_func, async_event: bool = False, lua: bool | object = None): ...
    @staticmethod
    async def call_async_event(event_name, *args, **kwargs) -> list[Any]: ...
    @staticmethod
    def call_event(event_name, *data, **kwargs) -> list[Any]: ...
    @staticmethod
    def call_lua_event(event_name, *data) -> list[Any]: ...
class ev(EventsSystem): ...
