from typing import Any


class EventsSystem:
    @staticmethod
    def register_event(event_name, event_func): ...
    @staticmethod
    async def call_async_event(event_name, *args, **kwargs) -> list[Any]: ...
    @staticmethod
    def call_event(event_name, *data, **kwargs) -> list[Any]: ...
class ev(EventsSystem): ...
